version: "1.1" # 不要修改
Debug: false

messages:
  prefix: '&f[&eCustomScreenMenu&f] '
  command_blocked: '&c固定视角下无法使用命令!'

sound:
  name: 'music.menu'
  volume: 1
  pitch: 1
  # 循环音效
  loop:
    # 是否开启
    enabled: true
    # 每隔多少秒播放一次
    duration: 30

# 加入游戏就执行菜单
join-run:
  enabled: false
  # 延迟多少秒执行
  delay: 3
  # 执行的菜单
  menu: 'test'

cursor-item:
  material: 'ARROW'
  custom-model-data: 0
  scale: 0.5
  # 最大3个X轴 已经为屏幕横向可容纳最大
  max-x: 3
  # 最大1.5个Y轴 已经为屏幕纵向可容纳最大
  max-y: 1.5
  # 光标Z轴偏移量
  z-offset: 0.0



menu:
  test:
    # 按钮所在的位置
    camera-position:
      # 与文字组件的距离
      distance: 1.5
      world: "world"
      x: 0
      y: 2
      z: 0
    layout:
      # 文字组件1
      layout1:
        name: "开始游戏"
        # 文字组件的x轴
        x: 0
        # 文字组件的y轴
        y: 0
        # 点击的执行命令
        z: 0.0
        command:
          - '[player] say test'
          - '[op] give %player% stone 1'
        # 点击后是否结束菜单
        stop-menu:
          enabled: false
          # 结束后传送
          teleport:
            enabled: false
            # 返回原本位置 或 返回指定位置
            back-original: true
            world: 'world'
            x: 10
            y: 80
            z: 10
          # 结束后执行的命令
          command:
            enabled: false
            list:
              - '[player] say stop'

      # 文字组件2
      layout2:
        name: "选项设置"
        x: 0
        y: -1
        z: 0.0
        command:
          - '[player] say test'
          - '[op] give %player% stone 1'
        stop-menu:
          enabled: false
          teleport:
            enabled: false
            world: 'world'
            x: 20
            y: 90
            z: 20
          command:
            enabled: false
            list:
              - '[player] say stop'

  lobby:
    camera-position:
      distance: 2
      world: "world"
      x: 0
      y: 100
      z: 0
    layout:
      layout1:
        name: "Start"
        x: 0
        y: 0
        command:
          - '[player] say test'
          - '[op] give %player% stone 1'
        stop-menu:
          enabled: false
          teleport:
            enabled: false
            world: 'world'
            x: 10
            y: 80
            z: 10
          command:
            enabled: false
            list:
              - '[player] say stop'

      layout2:
        name: "Options"
        x: 0
        y: -1
        command:
          - '[player] say test'
          - '[op] give %player% stone 1'
        stop-menu:
          enabled: false
          teleport:
            enabled: false
            world: 'world'
            x: 20
            y: 90
            z: 20
          command:
            enabled: false
            list:
              - '[player] say stop'